//*************************************************************************
// DESCRIPTION: HDLObf: Identifier Name Change Module
//
// Code available from: https://sourceforge.net/projects/hdlobf/
//
// AUTHORS: Vispi Cassod
//
//*************************************************************************
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of either the GNU General Public License or the
// Perl Artistic License.
//
// Verilator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//*************************************************************************
import javax.swing.*;
import java.io.*;
import java.util.*;
public class HDLObf extends java.awt.Frame {
    
    /** Creates new form HDLObf */
    public HDLObf() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLbl_Title = new javax.swing.JLabel();
        jButton_Convert = new javax.swing.JButton();
        jText_Source_File = new javax.swing.JTextField();
        jText_Target_File = new javax.swing.JTextField();
        jText_Map_File_In = new javax.swing.JTextField();
		jText_Map_File_Out = new javax.swing.JTextField();
        jButton_SrcBrowse = new javax.swing.JButton();
        jButton_TargetBrowse = new javax.swing.JButton();
        jButton_MapBrowse_In = new javax.swing.JButton();
        jButton_MapBrowse_Out = new javax.swing.JButton();
        jLbl_Source = new javax.swing.JLabel();
        jLbl_Target = new javax.swing.JLabel();
        jLbl_Map_In = new javax.swing.JLabel();
        jLbl_Map_Out = new javax.swing.JLabel();
        jLbl_Op = new javax.swing.JLabel();
        jCmb_Op = new javax.swing.JComboBox();
        jCmb_LOp = new javax.swing.JComboBox();
        jLbl_LOp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(null);

        setLocationRelativeTo(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLbl_Title.setFont(new java.awt.Font("Dialog", 1, 12));
        jLbl_Title.setText("HDL Obfuscator");
        jLbl_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLbl_Title);
        jLbl_Title.setBounds(100, 20, 350, 30);

        jButton_Convert.setText("Convert");
        jButton_Convert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ConvertMouseClicked(evt);
            }
        });

        add(jButton_Convert);
        jButton_Convert.setBounds(90, 260, 140, 25);

        jText_Source_File.setText("Enter source text file name");
        jText_Source_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Source_FileActionPerformed(evt);
            }
        });
        jText_Source_File.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jText_Source_FileFocusLost(evt);
            }
        });

        add(jText_Source_File);
        jText_Source_File.setBounds(90, 70, 190, 22);

        jText_Target_File.setText("Enter target text file name");
        add(jText_Target_File);
        jText_Target_File.setBounds(90, 100, 190, 22);

        jText_Map_File_In.setText("Enter Map text input file name");
        add(jText_Map_File_In);
        jText_Map_File_In.setBounds(90, 130, 190, 22);

		jText_Map_File_Out.setText("Enter Map text output file name");
        add(jText_Map_File_Out);
        jText_Map_File_Out.setBounds(90, 160, 190, 22);

        jButton_SrcBrowse.setText("Browse");
        jButton_SrcBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SrcBrowseActionPerformed(evt);
            }
        });

        add(jButton_SrcBrowse);
        jButton_SrcBrowse.setBounds(300, 70, 110, 25);
        
        jButton_TargetBrowse.setText("Browse");
        jButton_TargetBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TargetBrowseActionPerformed(evt);
            }
        });

        add(jButton_TargetBrowse);
        jButton_TargetBrowse.setBounds(300, 100, 110, 25);

        jButton_MapBrowse_In.setText("Browse");
        jButton_MapBrowse_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MapInBrowseActionPerformed(evt);
            }
        });

        add(jButton_MapBrowse_In);
        jButton_MapBrowse_In.setBounds(300, 130, 110, 25);

	jButton_MapBrowse_Out.setText("Browse");
        jButton_MapBrowse_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MapOutBrowseActionPerformed(evt);
            }
        });

        add(jButton_MapBrowse_Out);
        jButton_MapBrowse_Out.setBounds(300, 160, 110, 25);

        jLbl_Source.setText("Source file");
        add(jLbl_Source);
        jLbl_Source.setBounds(10, 70, 120, 16);

        jLbl_Target.setText("Target file");
        add(jLbl_Target);
        jLbl_Target.setBounds(10, 100, 110, 16);

        jLbl_Map_In.setText("MapI file");
        add(jLbl_Map_In);
        jLbl_Map_In.setBounds(10, 130, 100, 16);

 	jLbl_Map_Out.setText("MapO file");
        add(jLbl_Map_Out);
        jLbl_Map_Out.setBounds(10, 160, 100, 16);

        jLbl_Op.setText("Operation");
        add(jLbl_Op);
        jLbl_Op.setBounds(10, 190, 130, 16);

        jCmb_Op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_OpActionPerformed(evt);
            }
        });

        add(jCmb_Op);
        jCmb_Op.setBounds(90, 190, 190, 22);

        add(jCmb_LOp);
        jCmb_LOp.setBounds(90, 220, 190, 22);

        jLbl_LOp.setText("Language");
        add(jLbl_LOp);
        jLbl_LOp.setBounds(10, 220, 130, 16);

        add(jSeparator1);
        jSeparator1.setBounds(20, 52, 510, 0);

        pack();
    }//GEN-END:initComponents

    private void jButton_ConvertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ConvertMouseClicked
        performConvertAction();
    }//GEN-LAST:event_jButton_ConvertMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jCmb_Op.addItem("Obfuscator Tool");

        jCmb_LOp.addItem("Verilog");
        jCmb_LOp.addItem("VHDL");
        this.setBounds(10,10,500,350);
        
    }//GEN-LAST:event_formWindowOpened

    private void jCmb_OpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_OpActionPerformed
        
    }//GEN-LAST:event_jCmb_OpActionPerformed

    private void jButton_MapInBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MapInBrowseActionPerformed
        if( this.openFile(1) == false)
            javax.swing.JOptionPane.showMessageDialog(null, "False file selection", "alert", JOptionPane.ERROR_MESSAGE);
 
    }//GEN-LAST:event_jButton_MapInBrowseActionPerformed

   private void jButton_MapOutBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MapOutBrowseActionPerformed
        if( this.openFile(2) == false)
            javax.swing.JOptionPane.showMessageDialog(null, "False file selection", "alert", JOptionPane.ERROR_MESSAGE);
 
    }//GEN-LAST:event_jButton_MapInBrowseActionPerformed

    private void jButton_SrcBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SrcBrowseActionPerformed
        if( this.openFile(0) == false)
            javax.swing.JOptionPane.showMessageDialog(null, "False file selection", "alert", JOptionPane.ERROR_MESSAGE);
        this.setTargetPath();
    }//GEN-LAST:event_jButton_SrcBrowseActionPerformed
    
    private void jButton_TargetBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TargetcBrowseActionPerformed
        if( this.openFile(3) == false)
            javax.swing.JOptionPane.showMessageDialog(null, "False file selection", "alert", JOptionPane.ERROR_MESSAGE);
        this.setTargetPath();
    }//GEN-LAST:event_jButton_SrcBrowseActionPerformed

    private void jText_Source_FileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText_Source_FileFocusLost
        this.setTargetPath();
    }//GEN-LAST:event_jText_Source_FileFocusLost

    private void jText_Source_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Source_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_Source_FileActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HDLObf().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Convert;
    private javax.swing.JButton jButton_MapBrowse_In;
    private javax.swing.JButton jButton_MapBrowse_Out;
    private javax.swing.JButton jButton_SrcBrowse;
    private javax.swing.JButton jButton_TargetBrowse;
    private javax.swing.JComboBox jCmb_LOp;
    private javax.swing.JComboBox jCmb_Op;
    private javax.swing.JLabel jLbl_LOp;
    private javax.swing.JLabel jLbl_Map_In;
    private javax.swing.JLabel jLbl_Map_Out;
    private javax.swing.JLabel jLbl_Op;
    private javax.swing.JLabel jLbl_Source;
    private javax.swing.JLabel jLbl_Target;
    private javax.swing.JLabel jLbl_Title;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jText_Map_File_In;
    private javax.swing.JTextField jText_Map_File_Out;
    private javax.swing.JTextField jText_Source_File;
    private javax.swing.JTextField jText_Target_File;
    // End of variables declaration//GEN-END:variables
    
    
  private boolean openFile(int opt)
  {

    JFileChooser fc = new JFileChooser();
    fc.setDialogTitle("Open File");

    // Choose only files, not directories
    fc.setFileSelectionMode( JFileChooser.FILES_ONLY);

    // Start in current directory
    fc.setCurrentDirectory(new java.io.File("."));

    // Now open chooser
    int result = fc.showOpenDialog(this);

    if( result == JFileChooser.CANCEL_OPTION)
    {
      return true;
    }else if( result == JFileChooser.APPROVE_OPTION)
    {
        if(opt == 0)
            jText_Source_File.setText(fc.getSelectedFile().getAbsolutePath());      
        else if (opt == 1)
            jText_Map_File_In.setText(fc.getSelectedFile().getAbsolutePath());
        else if (opt == 2)
			jText_Map_File_Out.setText(fc.getSelectedFile().getAbsolutePath());
        else if (opt == 3)
			jText_Target_File.setText(fc.getSelectedFile().getAbsolutePath());   
        else
            return false;
    }else
    {
      return false;
    }
    return true;
  }
  // setting target path
   private void setTargetPath()
  {  
      if( ((jText_Target_File.getText()).compareTo("Enter target text file name") == 0) && ((jText_Source_File.getText()).compareTo("Enter source text file name") != 0)) 
            jText_Target_File.setText(jText_Source_File.getText() + ".out");  
   }
   // perform the main action
   private void performConvertAction()
   {
      String selectedLanguage = "";

      try
      {
         switch(jCmb_LOp.getSelectedIndex() )
         {
            case 0: selectedLanguage = "ver"; break;
            case 1: selectedLanguage = "vhd"; break;
         }



         if(jCmb_Op.getSelectedIndex() == 0 )                        
         {                                                           
            Obfuscate    obf      = new Obfuscate();
            obf.processFile(selectedLanguage, jText_Map_File_In.getText(), jText_Map_File_Out.getText(), jText_Source_File.getText(), jText_Target_File.getText());
            javax.swing.JOptionPane.showMessageDialog(null, "Obfuscation process completed!", "HDLObf", JOptionPane.INFORMATION_MESSAGE);
           
         } 
         else
         { 
            System.out.println("Unrecognized operation");
           
         } 
      }
      catch(Exception e)
      {
         System.out.println("Main Error: " + e.getMessage());
      }
   }
}
