BASE_DIR=`pwd`
LIB_DIR="${BASE_DIR}/../lib"
ANTLR_RELEASE="4.7.1"
ANTLR_DIR="${LIB_DIR}/antlr-${ANTLR_RELEASE}.jar"
BIN_DIR="${BASE_DIR}/../bin"
export CLASSPATH=".:${ANTLR_DIR}:${BIN_DIR}:$CLASSPATH"
